# Dockerfile for building a custom Kafka image
FROM python:latest
WORKDIR consumer
# Upgrade pip
RUN pip install --upgrade pip

# Intall libraries
RUN pip install confluent-kafka && pip install requests && pip install certifi && pip install confluent-kafka[avro,json,protobuf]>=1.4.2

#Copy files
COPY consumer.py ./consumer.py
COPY ccloud_lib.py ./ccloud_lib.py
COPY python.config  ./python.config

CMD ["python3","consumer.py"]